use std::time::Instant;
use wasmtime::{Config, Engine, Linker, Module, Store};
use wasmtime_wasi::preview1::{self, WasiP1Ctx};
use wasmtime_wasi::WasiCtxBuilder;

use crate::{error::RuntimeError, Manifest, Result, RunMetrics, RunResult, Runner};

pub struct WasmtimeRunner;

impl WasmtimeRunner {
    pub fn new() -> Self {
        Self
    }
}

impl Default for WasmtimeRunner {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait::async_trait]
impl Runner for WasmtimeRunner {
    async fn run(&self, manifest: Manifest) -> Result<RunResult> {
        let start = Instant::now();

        if manifest.image_cid.is_empty() {
            return Err(RuntimeError::InvalidManifest("empty image_cid".into()));
        }
        if manifest.entrypoint.is_empty() {
            return Err(RuntimeError::InvalidManifest("empty entrypoint".into()));
        }
        if manifest.max_duration_secs == 0 || manifest.max_duration_secs > 3600 {
            return Err(RuntimeError::InvalidManifest(
                "max_duration out of range (1-3600)".into(),
            ));
        }

        let wasm_bytes = load_wasm_image(&manifest.image_cid).await?;

        let mut config = Config::new();
        config.consume_fuel(true);
        let engine = Engine::new(&config).map_err(|e| RuntimeError::Execution(e.to_string()))?;

        let module = Module::new(&engine, &wasm_bytes)
            .map_err(|e| RuntimeError::Execution(format!("invalid wasm: {e}")))?;

        let wasi_ctx = WasiCtxBuilder::new()
            .inherit_stdio()
            .args(&["wasm", &manifest.entrypoint])
            .build_p1();

        let mut store = Store::new(&engine, wasi_ctx);
        store
            .set_fuel(manifest.max_duration_secs * 100_000)
            .map_err(|e| RuntimeError::Execution(e.to_string()))?;

        let mut linker: Linker<WasiP1Ctx> = Linker::new(&engine);
        preview1::add_to_linker_sync(&mut linker, |t| t)
            .map_err(|e| RuntimeError::Execution(e.to_string()))?;

        let instance = linker
            .instantiate(&mut store, &module)
            .map_err(|e| RuntimeError::Execution(e.to_string()))?;

        let func = instance
            .get_typed_func::<(), ()>(&mut store, &manifest.entrypoint)
            .or_else(|_| instance.get_typed_func::<(), ()>(&mut store, "_start"))
            .map_err(|e| RuntimeError::Execution(format!("entrypoint not found: {e}")))?;

        let blocking_task = tokio::task::spawn_blocking(move || {
            func.call(&mut store, ())
                .map_err(|e| RuntimeError::Execution(e.to_string()))
        });

        let timeout = std::time::Duration::from_secs(manifest.max_duration_secs);
        let result = tokio::time::timeout(timeout, blocking_task).await;

        let elapsed = start.elapsed();

        match result {
            Ok(Ok(Ok(()))) => Ok(RunResult {
                stdout: String::new(),
                stderr: String::new(),
                exit_code: 0,
                metrics: RunMetrics {
                    cpu_usage_percent: 0.0,
                    memory_usage_mb: 0.0,
                    duration_secs: elapsed.as_secs_f64(),
                },
            }),
            Ok(Ok(Err(e))) => Err(e),
            Ok(Err(e)) => Err(RuntimeError::Execution(format!("task failed: {e}"))),
            Err(_) => Err(RuntimeError::Timeout(manifest.max_duration_secs)),
        }
    }
}

/// A minimal valid WASM module that exports `_start` and does nothing.
/// Bytes generated by `wat2wasm` from: `(module (func (export "_start")))`
#[allow(unused)]
pub(crate) const MINIMAL_WASM: &[u8] = &[
    0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00, // magic + version
    0x01, 0x04, 0x01, 0x60, 0x00, 0x00, // type section
    0x03, 0x02, 0x01, 0x00, // function section
    0x07, 0x0a, 0x01, 0x06, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x00, 0x00, // export "_start"
    0x0a, 0x04, 0x01, 0x02, 0x00, 0x0b, // code section
];

fn wasm_cache_dir() -> std::path::PathBuf {
    std::env::temp_dir().join("flovenet").join("wasm_cache")
}

async fn load_wasm_image(cid: &str) -> std::result::Result<Vec<u8>, RuntimeError> {
    let cache_path = wasm_cache_dir().join(cid);
    if let Ok(data) = tokio::fs::read(&cache_path).await {
        return Ok(data);
    }

    let local_path = format!("wasm_images/target/wasm32-wasi/release/{cid}.wasm");
    tokio::fs::read(&local_path)
        .await
        .map_err(|e| RuntimeError::Execution(format!("cannot load wasm image {cid}: {e}")))
}

#[cfg(test)]
mod tests {
    use super::*;

    // --- Validation tests (no WASM needed) ---

    #[tokio::test]
    async fn test_rejects_empty_image_cid() {
        let runner = WasmtimeRunner::new();
        let manifest = Manifest {
            image_cid: "".into(),
            entrypoint: "_start".into(),
            args: vec![],
            max_duration_secs: 10,
            slots_required: 1,
            gpu_vram_gb: None,
        };
        let err = runner.run(manifest).await.unwrap_err();
        match err {
            RuntimeError::InvalidManifest(msg) => assert!(msg.contains("image_cid")),
            other => panic!("expected InvalidManifest, got {other}"),
        }
    }

    #[tokio::test]
    async fn test_rejects_empty_entrypoint() {
        let runner = WasmtimeRunner::new();
        let manifest = Manifest {
            image_cid: "test.wasm".into(),
            entrypoint: "".into(),
            args: vec![],
            max_duration_secs: 10,
            slots_required: 1,
            gpu_vram_gb: None,
        };
        let err = runner.run(manifest).await.unwrap_err();
        match err {
            RuntimeError::InvalidManifest(msg) => assert!(msg.contains("entrypoint")),
            other => panic!("expected InvalidManifest, got {other}"),
        }
    }

    #[tokio::test]
    async fn test_rejects_zero_duration() {
        let runner = WasmtimeRunner::new();
        let manifest = Manifest {
            image_cid: "test.wasm".into(),
            entrypoint: "_start".into(),
            args: vec![],
            max_duration_secs: 0,
            slots_required: 1,
            gpu_vram_gb: None,
        };
        let err = runner.run(manifest).await.unwrap_err();
        assert!(err.to_string().contains("out of range"));
    }

    #[tokio::test]
    async fn test_rejects_excessive_duration() {
        let runner = WasmtimeRunner::new();
        let manifest = Manifest {
            image_cid: "test.wasm".into(),
            entrypoint: "_start".into(),
            args: vec![],
            max_duration_secs: 3601,
            slots_required: 1,
            gpu_vram_gb: None,
        };
        let err = runner.run(manifest).await.unwrap_err();
        assert!(err.to_string().contains("out of range"));
    }

    #[tokio::test]
    async fn test_rejects_missing_wasm_file() {
        let runner = WasmtimeRunner::new();
        let manifest = Manifest {
            image_cid: "nonexistent-test-wasm".into(),
            entrypoint: "_start".into(),
            args: vec![],
            max_duration_secs: 10,
            slots_required: 1,
            gpu_vram_gb: None,
        };
        let err = runner.run(manifest).await.unwrap_err();
        assert!(err.to_string().contains("cannot load wasm image"));
    }

    // --- Real WASM execution test ---

    #[tokio::test]
    async fn test_real_wasm_execution() {
        let cid = "minimal-test-wasm";
        let cache_dir = wasm_cache_dir();
        tokio::fs::create_dir_all(&cache_dir).await.unwrap();
        tokio::fs::write(cache_dir.join(cid), MINIMAL_WASM)
            .await
            .unwrap();

        let runner = WasmtimeRunner::new();
        let manifest = Manifest {
            image_cid: cid.into(),
            entrypoint: "_start".into(),
            args: vec![],
            max_duration_secs: 30,
            slots_required: 1,
            gpu_vram_gb: None,
        };

        let result = runner.run(manifest).await.unwrap();
        assert_eq!(result.exit_code, 0);
        assert!(result.metrics.duration_secs > 0.0);
    }

    #[tokio::test]
    async fn test_real_wasm_execution_with_timeout() {
        let cid = "minimal-test-wasm-timeout";
        let cache_dir = wasm_cache_dir();
        tokio::fs::create_dir_all(&cache_dir).await.unwrap();
        tokio::fs::write(cache_dir.join(cid), MINIMAL_WASM)
            .await
            .unwrap();

        let runner = WasmtimeRunner::new();
        let manifest = Manifest {
            image_cid: cid.into(),
            entrypoint: "_start".into(),
            args: vec![],
            // Even though the timeout is very short, the WASM module
            // finishes instantly, so this should still succeed
            max_duration_secs: 1,
            slots_required: 1,
            gpu_vram_gb: None,
        };

        let result = runner.run(manifest).await.unwrap();
        assert_eq!(result.exit_code, 0);
    }

    #[tokio::test]
    async fn test_wasm_invalid_bytes() {
        let cid = "invalid-wasm-test";
        let cache_dir = wasm_cache_dir();
        tokio::fs::create_dir_all(&cache_dir).await.unwrap();
        tokio::fs::write(cache_dir.join(cid), b"not a valid wasm binary")
            .await
            .unwrap();

        let runner = WasmtimeRunner::new();
        let manifest = Manifest {
            image_cid: cid.into(),
            entrypoint: "_start".into(),
            args: vec![],
            max_duration_secs: 10,
            slots_required: 1,
            gpu_vram_gb: None,
        };

        let err = runner.run(manifest).await.unwrap_err();
        assert!(err.to_string().contains("invalid wasm"));
    }
}
